<?php

namespace SBC\TiersBundle\Repository;
use SBC\TiersBundle\Entity\Supplier;

/**
 * SupplierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SupplierRepository extends TiersRepository
{
    /**
     * Overriding Entity Manager's find by id function
     * This function accept $code (string) instead of $id (integer)
     * @param mixed $code
     * @param null $lockMode
     * @param null $lockVersion
     * @return null|Supplier
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function find($code, $lockMode = null, $lockVersion = null)
    {
        $qb = $this->createQueryBuilder('s');
        $qb->select('s, ma, ad, cnt')
            ->join('s.mainAddress', 'ma')
            ->leftJoin('s.addresses', 'ad')
            ->leftJoin('s.contacts', 'cnt')
            ->where('s.code = :code')
            ->setParameter('code', $code)
        ;
        return $qb->getQuery()->getOneOrNullResult();
    }
}
