<?php

namespace SBC\TiersBundle\Repository;

/**
 * TiersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TiersRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Overriding Entity Manager's findAll function
     * This function get tiers joined with the main address in one query
     * @return array
     */
    public function findAll(){
        $qb = $this->createQueryBuilder('t');
        $qb->select('t, ma')
            ->join('t.mainAddress', 'ma');

        return $qb->getQuery()->getResult();
    }

    /**
     * Get all not archived tiers
     * @return array
     */
    public function findNotArchived(){
        $qb = $this->createQueryBuilder('t');
        $qb->select('t, ma')
            ->join('t.mainAddress', 'ma')
            ->where('t.archived = :f')
            ->setParameter('f', false)
        ;

        return $qb->getQuery()->getResult();
    }
}
