services:
#    bien.example:
#        class: SBC\BienBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    history.service:
        class: SBC\BienBundle\EventListener\HistoryService
        arguments: ["@security.token_storage"]
        tags:
            - { name: doctrine.event_subscriber, connection: default }