<?php

namespace SBC\GeoTunisieBundle\Repository;

/**
 * AdresseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdresseRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAdressesByRueNotJoined($rue)
    {
        $qb2 = $this->createQueryBuilder('ad')
            ->from('SBC\BienBundle\Entity\Bien', 'bi')
            ->select('IDENTITY(bi.address)');

        $qb = $this->createQueryBuilder('a');
        return
            $qb->where('a.rue = :rue')
                ->setParameter('rue', $rue)
                ->andWhere(
                    $qb->expr()->notIn('a.id', $qb2->getDQL())
                )
                ->getQuery()
                ->getResult();
    }
}
