<?php

namespace SBC\GeoTunisieBundle\Repository;

/**
 * RueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RueRepository extends \Doctrine\ORM\EntityRepository
{

    /**
     * Search rues by reg
     * @param $reg
     * @return array
     */
    public function listeRuesByReg($reg)
    {
        $qb = $this->createQueryBuilder('rue');
        return $qb->where(
            $qb->expr()->like('rue.name', ':name')
        )
            ->setParameter('name', '%' . $reg . '%')
            ->getQuery()
            ->getResult();
    }
}
