<?php

namespace SBC\UserBundle\Repository;

/**
 * AccessHistoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AccessHistoryRepository extends \Doctrine\ORM\EntityRepository
{
    public function getLastAccess($user, $sessionId)
    {
        $query = $this->createQueryBuilder('a')
            ->leftJoin('a.user', 'u')
            ->addSelect('u')
            ->where('u.id = ?1 and a.logoutDate is null and a.sessionId = ?2')
            ->setParameters(array(1 => $user->getId(), 2 => $sessionId))
            ->getQuery();

        //if same user is connecteed more than one time so exception
        return $query
            ->getOneOrNullResult();
    }
}
