<?php

namespace SBC\MessageBundle\Repository;

/**
 * MessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessageRepository extends \Doctrine\ORM\EntityRepository
{


    public function findAll($me = null, $with = null)
    {
        $query = $this->createQueryBuilder('m')
            ->leftJoin('m.sender', 's')
            ->addSelect('s')
            ->leftJoin('s.personnel', 'spersonnel')
            ->addSelect('spersonnel')
            ->leftJoin('m.receiver', 'r')
            ->addSelect('r')
            ->leftJoin('r.personnel', 'rpersonnel')
            ->addSelect('rpersonnel')
            ->orderBy('m.creationdate', 'ASC')
            ->Where('m.sender= :me and m.receiver= :with ')
            ->orWhere('m.receiver= :me and m.sender= :with')
            ->setParameter('me', $me)
            ->setParameter('with', $with)
            ->setMaxResults(10)
            ->getQuery();

        return $query
            ->getArrayResult();
    }
}
