# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:

    sbc.fields.comparator:
        class: SBC\UtilsBundle\Utils\FieldsComparator
        arguments: ["@property_accessor", "@doctrine"]

