<?php

namespace SBC\ReclamationBundle\Repository;

/**
 * AttachmentReclamationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AttachmentReclamationRepository extends \Doctrine\ORM\EntityRepository
{
}
