<?php

namespace SBC\PersonnelBundle\Repository;

/**
 * AddressPersonnelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AddressPersonnelRepository extends \Doctrine\ORM\EntityRepository
{
}
