<?php

namespace SBC\BienBundle\Repository;

/**
 * AcceptationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AcceptationRepository extends \Doctrine\ORM\EntityRepository
{
}
