<?php

namespace SBC\BienBundle\Repository;

/**
 * AcquisitionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AcquisitionRepository extends \Doctrine\ORM\EntityRepository
{

//    public function findAll($rueID = null)
//    {
//
//        $query = $this->createQueryBuilder('a')
//            ->leftJoin('a.bien', 'b')
//            ->addSelect('b')
//            ->leftJoin('b.agency', 'ag')
//            ->addSelect('ag')
//            ->leftJoin('b.createdBy', 'c')
//            ->addSelect('c')
//            ->leftJoin('b.equipements', 'e')
//            ->addSelect('e')
//            ->leftJoin('b.owners', 'owners')
//            ->addSelect('owners')
//            ->leftJoin('owners.client', 'client')
//            ->addSelect('client')
//            ->leftJoin('b.representants', 'representants')
//            ->addSelect('representants')
//            ->leftJoin('representants.client', 'clientt')
//            ->addSelect('clientt')
//            ->leftJoin('representants.representant', 'representant')
//            ->addSelect('representant')
//            ->leftJoin('b.procurations', 'procurations')
//            ->addSelect('procurations')
//            ->leftJoin('procurations.client', 'clienttt')
//            ->addSelect('clienttt')
//            ->leftJoin('procurations.representant', 'representantt')
//            ->addSelect('representantt')
//
//
//            ->leftJoin('b.pictures', 'p')
//            ->addSelect('p')
//            ->leftJoin('b.address', 'addr')
//            ->addSelect('addr')
//            ->leftJoin('addr.rue', 'rue')
//            ->addSelect('rue')
//            ->leftJoin('rue.localite', 'localite')
//            ->addSelect('localite')
//            ->leftJoin('localite.ville', 'ville')
//            ->addSelect('ville')
//            ->leftJoin('ville.gouvernorat', 'gouvernorat')
//            ->addSelect('gouvernorat')
//            ->leftJoin('b.typeBien', 't')
//            ->addSelect('t')
//            ->leftJoin('t.category', 'categ')
//            ->addSelect('categ')
//            ->leftJoin('b.commodites', 'com')
//            ->addSelect('com')
//            ->leftJoin('b.address', 'address')
//            ->addSelect('address')
//
//            ->orderBy('a.creationDate','DESC')
//        ;
//
//           // return for JSON
//        if ($rueID != null) {
//            $query->andWhere('address.rue = :id')->setParameter('id', $rueID);
//            return $query->getQuery()->getArrayResult();
//        }
//        // return for list
//        return $query->getQuery()->getResult();
//    }


//    public function find($id, $lockMode = null, $lockVersion = null)
//    {
//
//        $query = $this->createQueryBuilder('a')
//            ->leftJoin('a.bien', 'b')
//            ->addSelect('b')
//            ->leftJoin('b.agency', 'ag')
//            ->addSelect('ag')
//            ->leftJoin('b.createdBy', 'c')
//            ->addSelect('c')
//            ->leftJoin('b.equipements', 'e')
//            ->addSelect('e')
//            ->leftJoin('b.owners', 'owners')
//            ->addSelect('owners')
//            ->leftJoin('owners.client', 'client')
//            ->addSelect('client')
////            ->leftJoin('b.representants', 'representants')
////            ->addSelect('representants')
////            ->leftJoin('representants.client', 'clientt')
////            ->addSelect('clientt')
////            ->leftJoin('representants.representant', 'representant')
////            ->addSelect('representant')
//            ->leftJoin('b.procurations', 'procurations')
//            ->addSelect('procurations')
//            ->leftJoin('procurations.client', 'clienttt')
//            ->addSelect('clienttt')
//            ->leftJoin('procurations.representant', 'representantt')
//            ->addSelect('representantt')
//
//            ->leftJoin('b.pictures', 'p')
//            ->addSelect('p')
//            ->leftJoin('b.address', 'addr')
//            ->addSelect('addr')
//            ->leftJoin('addr.rue', 'rue')
//            ->addSelect('rue')
//            ->leftJoin('rue.localite', 'localite')
//            ->addSelect('localite')
//            ->leftJoin('localite.ville', 'ville')
//            ->addSelect('ville')
//            ->leftJoin('ville.gouvernorat', 'gouvernorat')
//            ->addSelect('gouvernorat')
//            ->leftJoin('b.typeBien', 't')
//            ->addSelect('t')
//            ->leftJoin('t.category', 'categ')
//            ->addSelect('categ')
//            ->leftJoin('b.commodites', 'com')
//            ->addSelect('com')
//            ->leftJoin('a.taches', 'ta')
//            ->addSelect('ta')
//            ->leftJoin('ta.typeTache', 'tya')
//            ->addSelect('tya')
//            ->leftJoin('ta.personnel', 'pers')
//            ->addSelect('pers')
//
//            ->leftJoin('a.meetings', 'meetings')
//            ->addSelect('meetings')
//            ->leftJoin('meetings.remindFors', 'remind_for')
//            ->addSelect('remind_for')
//            ->where('a.id = ?1')
//            ->getQuery();
//        $query->setParameters(array(1 => $id));
//
//        return $query->getOneOrNullResult();
//    }
}
