<?php

namespace SBC\BienBundle\Repository;

/**
 * AcquisitionMeetingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AcquisitionMeetingRepository extends \Doctrine\ORM\EntityRepository
{
}
