<?php

namespace SBC\BienBundle\Repository;

/**
 * ActivityGroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActivityGroupRepository extends \Doctrine\ORM\EntityRepository
{
}
