<?php

namespace SBC\BienBundle\Repository;

/**
 * BienAttachementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BienAttachementRepository extends \Doctrine\ORM\EntityRepository
{
}
