<?php

namespace SBC\BienBundle\Repository;

/**
 * BienGallerieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BienGallerieRepository extends \Doctrine\ORM\EntityRepository
{
}
