<?php

namespace SBC\BienBundle\Repository;

/**
 * BienPictureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BienPictureRepository extends \Doctrine\ORM\EntityRepository
{
}
