<?php

namespace SBC\BienBundle\Repository;

/**
 * BienMeetingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BienMeetingRepository extends \Doctrine\ORM\EntityRepository
{
}
