<?php

namespace SBC\BienBundle\Repository;

/**
 * CanalisationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CanalisationRepository extends \Doctrine\ORM\EntityRepository
{
}
