<?php

namespace SBC\BienBundle\Repository;

/**
 * CommisionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommisionRepository extends \Doctrine\ORM\EntityRepository
{
}
