<?php

namespace SBC\BienBundle\Repository;

/**
 * CommoditeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommoditeRepository extends \Doctrine\ORM\EntityRepository
{
}
