<?php

namespace SBC\BienBundle\Repository;

/**
 * CongeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CongeRepository extends \Doctrine\ORM\EntityRepository
{
}
