<?php

namespace SBC\BienBundle\Repository;

/**
 * ContratRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContratRepository extends \Doctrine\ORM\EntityRepository
{

    public function findAll()
    {

        $query = $this->createQueryBuilder('c')
            ->leftJoin('c.typeContrat', 't')
            ->addSelect('t')
            ->leftJoin('c.bien', 'b')
            ->addSelect('b')
            ->orderBy('c.creationDate','DESC')
            ->getQuery();

        return $query->getResult();
    }

    public function find($id, $lockMode = null, $lockVersion = null)
    {

        $query = $this->createQueryBuilder('c')
            ->leftJoin('c.typeContrat', 't')
            ->addSelect('t')
            ->leftJoin('c.bien', 'b')
            ->addSelect('b')
            ->where('c.id = ?1')
            ->getQuery();
        $query->setParameters(array(1 => $id));

        return $query->getOneOrNullResult();
    }

    public function invalidateContratsOfBien($bien)
    {

//        $query = $this->_em->createQueryBuilder();
//
//           $qb = $query->update('BienBundle:Contrat', 'c')
//            ->set('c.valide', $qb->expr()->literal($bien->getId()))
//        ->where('c.id = ?1')
//        ->setParameters(array(1 => $bien->getId()))
//        ->getQuery();
//        return $qb->execute();
//


         $qb= $this->createQueryBuilder('c');
        return  $qb->update()
             ->set('c.valide', '?1')
             ->setParameter(1, $qb->expr()->literal(0))
             ->where('c.bien = ?2')
             ->setParameter(2, $qb->expr()->literal($bien->getId()))
             ->getQuery()->getSingleScalarResult();
    }
}
