<?php

namespace SBC\BienBundle\Repository;

/**
 * EnQualiteDeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EnQualiteDeRepository extends \Doctrine\ORM\EntityRepository
{
}
