<?php

namespace SBC\BienBundle\Repository;

/**
 * ExterieurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExterieurRepository extends \Doctrine\ORM\EntityRepository
{
}
