<?php

namespace SBC\BienBundle\Repository;

use SBC\BienBundle\Entity\Goal;
use SBC\BienBundle\Entity\History;
use SBC\PersonnelBundle\Entity\Personnel;

/**
 * GoalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GoalRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAll()
    {
        $query = $this->createQueryBuilder('goal')
            ->leftJoin('goal.agency', 'agency')
            ->addSelect('agency')
            ->leftJoin('goal.createdBy', 'createdby')
            ->addSelect('createdby')
            ->leftJoin('goal.goalFor', 'goalfor')
            ->addSelect('goalfor')
            ->orderBy('goal.creationDate','DESC')
            ->getQuery();

        return $query->getResult();
    }

    public function find($id, $lockMode = null, $lockVersion = null)
    {

        $query = $this->createQueryBuilder('goal')
            ->leftJoin('goal.agency', 'agency')
            ->addSelect('agency')
            ->leftJoin('goal.createdBy', 'createdby')
            ->addSelect('createdby')
            ->leftJoin('goal.goalFor', 'goalfor')
            ->addSelect('goalfor')
            ->where('goal.id = ?1')
            ->getQuery()
            ->setParameters(array(1 => $id));

        return $query->getOneOrNullResult();
    }

    public function findGoal($date, Personnel $personnel)
    {

        $query = $this->createQueryBuilder('goal')
            ->leftJoin('goal.agency', 'agency')
            ->addSelect('agency')
            ->leftJoin('goal.createdBy', 'createdby')
            ->addSelect('createdby')
            ->leftJoin('goal.goalFor', 'goalfor')
            ->addSelect('goalfor')
            ->where('goalfor.id = ?1 and goal.beginDate <= ?2 and goal.finishDate >= ?3 and goal.agency = ?4')
            ->getQuery()
            ->setParameters(array(1 => $personnel->getId(), 2 => $date, 3 => $date, 4 => $personnel->getAgency()->getId()));
        return $query->getOneOrNullResult();

    }

//
//    public function checkIfAPersonnelHasAGoalAction($dateBegin, $finishDate = null, $goalFor = null)
//    {
//
//        $query = $this->createQueryBuilder('goal')
//            ->leftJoin('goal.agency', 'agency')
//            ->addSelect('agency')
//            ->leftJoin('goal.createdBy', 'createdby')
//            ->addSelect('createdby')
//            ->leftJoin('goal.goalFor', 'goalfor')
//            ->addSelect('goalfor');
//
//        if ($finishDate == null) {
//            $query->where(' goal.beginDate <= ?1 and goal.finishDate >= ?2 ')
//                ->setParameters(array(1 => $dateBegin, 2 => $dateBegin));
//        } else {
//            $query->where(' (goal.beginDate <= ?1 and goal.finishDate >= ?2) or ( goal.finishDate >= ?3 and goal.beginDate >= ?4 ) ')
//                ->setParameters(array(1 => $dateBegin, 2 => $finishDate, 3 =>$finishDate , 4 =>$dateBegin));
//        }
//
//
//        return $query->getQuery()->getOneOrNullResult();
//
//    }

}
