<?php

namespace SBC\BienBundle\Repository;

/**
 * MandatMeetingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MandatMeetingRepository extends \Doctrine\ORM\EntityRepository
{
}
