<?php

namespace SBC\BienBundle\Repository;

/**
 * NouvelleMeetingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NouvelleMeetingRepository extends \Doctrine\ORM\EntityRepository
{
}
