<?php

namespace SBC\BienBundle\Repository;

/**
 * NouvelleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NouvelleRepository extends \Doctrine\ORM\EntityRepository
{

    public function getAll($type,$type2)
    {

        $query = $this->createQueryBuilder('b')
            ->leftJoin('b.agency', 'a')
            ->addSelect('a')
            ->leftJoin('b.createdBy', 'c')
            ->addSelect('c')
            ->leftJoin('b.equipements', 'e')
            ->addSelect('e')
            ->leftJoin('b.owner', 'o')
            ->addSelect('o')
            ->leftJoin('b.pictures', 'p')
            ->addSelect('p')
            ->leftJoin('b.typeBien', 't')
            ->addSelect('t')
            ->leftJoin('t.category', 'categ')
            ->addSelect('categ')
            ->where('b.type =?1 or b.type =?2 ')
            ->setParameters(array(1 => $type, 2 => $type2))
            ->orderBy('b.creationDate','DESC')
            ->getQuery();

        return $query->getResult();
    }
}
