<?php

namespace SBC\BienBundle\Repository;

/**
 * OffreLocationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OffreLocationRepository extends \Doctrine\ORM\EntityRepository
{
}
