<?php

namespace SBC\BienBundle\Repository;

/**
 * OffreVenteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OffreVenteRepository extends \Doctrine\ORM\EntityRepository
{
}
