<?php

namespace SBC\BienBundle\Repository;

/**
 * OtherMeetingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OtherMeetingRepository extends \Doctrine\ORM\EntityRepository
{
}
