<?php

namespace SBC\BienBundle\Repository;

/**
 * PreferenceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PreferenceRepository extends \Doctrine\ORM\EntityRepository
{
}
