<?php

namespace SBC\BienBundle\Repository;

/**
 * ProcurationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProcurationRepository extends \Doctrine\ORM\EntityRepository
{
}
