<?php

namespace SBC\BienBundle\Repository;

/**
 * ProprietaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProprietaireRepository extends \Doctrine\ORM\EntityRepository
{
}
