<?php

namespace SBC\BienBundle\Repository;

/**
 * ProprietaireSelfRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProprietaireSelfRepository extends \Doctrine\ORM\EntityRepository
{
}
