<?php

namespace SBC\BienBundle\Repository;

/**
 * ProposalClientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProposalClientRepository extends \Doctrine\ORM\EntityRepository
{
}
