<?php

namespace SBC\BienBundle\Repository;

/**
 * RemindAcquisitionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RemindAcquisitionRepository extends \Doctrine\ORM\EntityRepository
{
}
