<?php

namespace SBC\BienBundle\Repository;

/**
 * RemindNouvelleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RemindNouvelleRepository extends \Doctrine\ORM\EntityRepository
{
}
