<?php

namespace SBC\BienBundle\Repository;

/**
 * RemindMandatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RemindMandatRepository extends \Doctrine\ORM\EntityRepository
{
}
