<?php

namespace SBC\BienBundle\Repository;

/**
 * RemindRequeteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RemindRequeteRepository extends \Doctrine\ORM\EntityRepository
{
}
