<?php

namespace SBC\BienBundle\Repository;
use SBC\PersonnelBundle\Entity\Personnel;
use SBC\UserBundle\Entity\User;

/**
 * RemindRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RemindRepository extends \Doctrine\ORM\EntityRepository
{

    public function findAll()
    {
        $query = $this->createQueryBuilder('remind')
            ->leftJoin('remind.remindFor', 'remindFor')
            ->addSelect('remindFor')
            ->leftJoin('remind.createdBy', 'createdby')
            ->addSelect('createdby')
            ->leftJoin('remindFor.agency', 'agency')
            ->addSelect('agency')
            ->leftJoin('remindFor.address', 'address')
            ->addSelect('address')
            ->getQuery();

        return $query
            ->getResult();
    }

    public function findByUser(Personnel $personnel)
    {
        $date = new \DateTime('now');

        $query = $this->createQueryBuilder('remind')
            ->leftJoin('remind.remindFor', 'remindFor')
            ->addSelect('remindFor')
            ->where('remind.remindFor = :personnel')
            ->andWhere('remind.beginDate >= :date')
            ->orderBy('remind.creationDate' , 'ASC')
            ->setParameter('personnel', $personnel)
            ->setParameter('date' , $date)
            ->getQuery();

        return $query
            ->getResult();
    }
}
