<?php

namespace SBC\BienBundle\Repository;

/**
 * RepresentantBienRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RepresentantBienRepository extends \Doctrine\ORM\EntityRepository
{
}
