<?php

namespace SBC\BienBundle\Repository;

/**
 * RepresentantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RepresentantRepository extends \Doctrine\ORM\EntityRepository
{
}
