<?php

namespace SBC\BienBundle\Repository;

/**
 * RequeteMeetingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RequeteMeetingRepository extends \Doctrine\ORM\EntityRepository
{
}
