<?php

namespace SBC\BienBundle\Repository;

/**
 * RequeteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RequeteRepository extends \Doctrine\ORM\EntityRepository
{

    public function findAll()
    {

        $query = $this->createQueryBuilder('r')
            ->leftJoin('r.client', 'c')
            ->addSelect('c')

            ->leftJoin('r.gouvernorats', 'g')
            ->addSelect('g')

            ->leftJoin('r.villes', 'v')
            ->addSelect('v')

            ->leftJoin('r.personnel', 'p')
            ->addSelect('p')

            ->leftJoin('r.typeBiens', 't')
            ->addSelect('t')

            ->leftJoin('r.commodites', 'com')
            ->addSelect('com')

            ->orderBy('r.creationDate','DESC')


            ->getQuery();

        return $query->getResult();
    }


    public function find($id, $lockMode = null, $lockVersion = null)
    {

        $query = $this->createQueryBuilder('r')
            ->leftJoin('r.client', 'c')
            ->addSelect('c')

            ->leftJoin('c.contacts', 'cnt')
            ->addSelect('cnt')

            ->leftJoin('r.gouvernorats', 'g')
            ->addSelect('g')

            ->leftJoin('r.villes', 'v')
            ->addSelect('v')

            ->leftJoin('r.personnel', 'p')
            ->addSelect('p')

            ->leftJoin('r.typeBiens', 't')
            ->addSelect('t')

            ->leftJoin('r.commodites', 'com')
            ->addSelect('com')

            ->leftJoin('r.origines', 'org')
            ->addSelect('org')

            ->leftJoin('r.equipements', 'eq')
            ->addSelect('eq')



            ->leftJoin('r.taches', 'ta')
            ->addSelect('ta')
            ->leftJoin('ta.typeTache', 'tya')
            ->addSelect('tya')
            ->leftJoin('ta.personnel', 'pers')
            ->addSelect('pers')

            ->leftJoin('r.proposals', 'proposals')
            ->addSelect('proposals')
            ->leftJoin('proposals.mandat', 'mandat')
            ->addSelect('mandat')
            ->leftJoin('mandat.acquisition', 'acquisition')
            ->addSelect('acquisition')
            ->leftJoin('acquisition.bien', 'bien')
            ->addSelect('bien')
            ->leftJoin('proposals.proposedBy', 'proposed_by')
            ->addSelect('proposed_by')
            ->leftJoin('proposals.proposedFor', 'proposed_for')
            ->addSelect('proposed_for')

            ->leftJoin('r.meetings', 'meetings')
            ->addSelect('meetings')
            ->leftJoin('meetings.remindFors', 'remind_for')
            ->addSelect('remind_for')

            ->where('r.id = ?1')
            ->getQuery();
        $query->setParameters(array(1 => $id));

        return $query->getOneOrNullResult();
    }

    public function generateReference()
    {
        $query = $this->createQueryBuilder('r')
            ->select('COUNT(r)')
        ->getQuery();
        return $query->getResult();
    }

}
