<?php

namespace SBC\BienBundle\Repository;

/**
 * ReunionMeetingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReunionMeetingRepository extends \Doctrine\ORM\EntityRepository
{
}
