<?php

namespace SBC\BienBundle\Repository;

/**
 * ReunionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReunionRepository extends \Doctrine\ORM\EntityRepository
{
}
