<?php

namespace SBC\BienBundle\Repository;

/**
 * TacheBienRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TacheBienRepository extends \Doctrine\ORM\EntityRepository
{
}
