<?php

namespace SBC\BienBundle\Repository;

/**
 * TacheMandatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TacheMandatRepository extends \Doctrine\ORM\EntityRepository
{
}
