<?php

namespace SBC\BienBundle\Repository;

/**
 * TacheNouvelleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TacheNouvelleRepository extends \Doctrine\ORM\EntityRepository
{
}
