<?php

namespace SBC\BienBundle\Repository;
use SBC\BienBundle\Entity\Goal;
use SBC\BienBundle\Entity\History;
use SBC\BienBundle\EventListener\HistoryService;
use SBC\PersonnelBundle\Entity\Personnel;

/**
 * TacheRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TacheRepository extends \Doctrine\ORM\EntityRepository
{

}
