<?php

namespace SBC\BienBundle\Repository;

/**
 * TacheAcquisitionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TacheAcquisitionRepository extends \Doctrine\ORM\EntityRepository
{
}
