<?php

namespace SBC\BienBundle\Repository;

/**
 * TacheRequeteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TacheRequeteRepository extends \Doctrine\ORM\EntityRepository
{
}
