<?php

namespace SBC\BienBundle\Repository;

/**
 * TypeTacheRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeTacheRepository extends \Doctrine\ORM\EntityRepository
{
}
