<?php

namespace SBC\BienBundle\Repository;

/**
 * TypeBienRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeBienRepository extends \Doctrine\ORM\EntityRepository
{

    public function findAll()
    {

        $query = $this->createQueryBuilder('tb')
            ->leftJoin('tb.category', 'categ')
            ->addSelect('categ')
            ->orderBy('tb.creationDate','DESC')
            ->getQuery();

        return $query->getResult();
    }

    public function find($id, $lockMode = null, $lockVersion = null)
    {

        $query = $this->createQueryBuilder('tb')
            ->leftJoin('tb.category', 'categ')
            ->addSelect('categ')
            ->where('tb.id = ?1')
            ->getQuery();
        $query->setParameters(array(1 => $id));

        return $query->getOneOrNullResult();
    }
}
