<?php

namespace SBC\BienBundle\Repository;

/**
 * VisiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VisiteRepository extends \Doctrine\ORM\EntityRepository
{
}
